console.log("My first console project");
var first_name="Reyansh";
var last_name="Sahoo";
var full_name=first_name.concat(last_name);
console.log(full_name);
var a=10;
var b=5;
var add=a+b;
console.log(add);
var sub=a-b;
console.log(sub);
var mul=a*b;
console.log(mul);
var div=a/b;
console.log(div);